export const data = {
  list: [
    {
      entity: {
        id: 6,
        parentMenuId: 0,
        name: "userManage",
        icon: "el-icon-news",
        alias: "用户管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于用户管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 7,
            parentMenuId: 6,
            name: "userList",
            icon: "el-icon-user\r\n",
            alias: "用户中心",
            state: "ENABLE",
            sort: 0,
            value: "/user",
            type: "NONE",
            discription: "用于帐号管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 9,
        parentMenuId: 0,
        name: "roleManage",
        icon: "el-icon-rank",
        alias: "权限管理",
        state: "ENABLE",
        sort: 2,
        value: null,
        type: "NONE",
        discription: "用于内容管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 10,
            parentMenuId: 9,
            name: "roleList",
            icon: "el-icon-s-tools\n\r\n",
            alias: "角色中心",
            state: "ENABLE",
            sort: 0,
            value: "/user",
            type: "NONE",
            discription: "角色中心",
            createUserId: 1,
          },
        },
        {
          entity: {
            id: 11,
            parentMenuId: 9,
            name: "authList",
            icon: "el-icon-help\r\n",
            alias: "资源中心",
            state: "ENABLE",
            sort: 0,
            value: "/user",
            type: "NONE",
            discription: "资源中心",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 12,
        parentMenuId: 0,
        name: "organManage",
        icon: "el-icon-news",
        alias: "组织管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于用户管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 12,
            parentMenuId: 12,
            name: "organList",
            icon: "el-icon-phone-outline\r\n",
            alias: "组织中心",
            state: "ENABLE",
            sort: 0,
            value: "/user",
            type: "NONE",
            discription: "用于帐号管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
  ],
};
